language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox
script: tox -e pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wgwz
  password:
    secure: q/S+rc7mMv47HEDSpgx8/YtH5o5/qRW1aPxq3B3mALWL2B0pNnxMd1vPDh1qcMo/6bYklCfLzCpxyga7A6qtSx7VHaw0m1rAzPow68QvQvrq6e/x88JFTjfJEsW1G1+TzEi2uEikbipGpWgMc1cCaKOf2FhXZldXYEmDZJiy+My9fuoaFNvAf5CxE/QSxTBM2Wt610fYtIn5nq5z5tDnS4Z4hlPF6GUIers0w8RqI2SNzimebBAQ/96nS9k0jUsY1ogmvg0NMRH47bkOUgA9vBXHowJkrpa+fLsHK26BAj2EDSdYaC0ftMTEAuiBzdc5GW8rCQryWSJpTg5Tz2MyuHpqGkYcUSRNcWmz/CU8BnAeAk0vOFn/RfEL2Rd0cxgat7Oo81n0t4EaeUbiZsPNFhrmGlU44LHr3rqJCY3G3ebpVIGEl3tUOOd8wDQHmyPYgHAnnHFbh1YHE0EH2mU/7isfQg+bg12P46tHhMmKeXnG9hMXroKq8dlG4mMg4qAKtXI5iPhv2pMWg1/vNGYKPH/Ucck6ueUZPtdKY1X6FRqv56HkWQbkMaIrkqiBPHi4VjcFLUUZSczYoa1f6iSvVxlNLKl9gerUYIfzMqQSWq5i9djjX5cAl12wVvj8dl27PbGRTWX4+rgvIYxBk5gPZp6BjFeAxsRfd0Z1NZhZkMs=
  on:
    tags: true
    python: 3.5
