language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox
script: tox -e pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wgwz
  password:
    secure: "SXa29zg93o74p1JgqwF0dPM6By/Zm/7FPu8mlL75myynJA0yxz9eVo9KKqSUdolUJNSag9QJdYZbiU00tjzajm6qZlSzS2mqL48CNT7cmZ0/bxlCHqZ+At2T0oMzS1vaifujbkQfosxITEPmY8XyNtGkaFEP9XfLGxCEW8rdNP/+rvmbN4MtBLeg3tz+qP24v2c3LYh5nobEpiB4AbRIsRBzF3He8f2VJKDF+B66dYqHzXgUXXpYnUTYwJ/npkgk1mrVV9/V2cRN51NsaZLlFhec02tHvuD4gMzJQBeM/GnhUYqqLVvz4L1V3ePpOPORvgXfSnbeEb6LJZkfSGK1ET9uh/00pOl2P74x6KOlWhz61Bz9Q/p1s2xjSJpW2x2capc6ELb0g+iokvRXIBTGViT22EvfdiuX4deh/vwQna0ceAud37xV8caAAV0FPzeZvdWd1Vf+Jo67rEooEB6N1FqTFGpbjVQDaMWaw1O3OmydmOeDl8z94wUdC6zx4qyiHoJ27b8aeCTG4TCHqdPbtVam4HNb7fP3ag5U+d6WL2aT3orwnKDn5czPf8f2UnkApLb22mJO4Dq9qPq1syZR7Kmj450kLlZmYb/nVr+ERuWOnpLPuzESwo5uvO9Mw4kjk5jDmlwnfVbwVvx0uzAvIjMb9ZcDJG2kDLwU4E7V3Kc="
  on:
    tags: true
    repo: wgwz/flask-decode
    python: 3.6
