language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox
script: tox -e pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wgwz
  password:
    secure: Hpvz+JzrUkJN9buj3sCQoZd/HYy3HePp4buypE5e10RNqcuyatit45gfSoZqmdtYYaULK+g5jJpuyb7XkG4MJmWSUyYmRd69Ps84aunL+12rOmUVSgap/vRkPiOw1Rbm/MRJN+prhJBPeBCBADARfheiGkyukRvXtkFYrIj8GL4uBgBJ6+51Ih+WNcc+Nzxzk1iMsEtlXBW7HTkjTFDgQFsFpGU4RDG2M9b8BZQyac60x7Oq4Fc+ARaCwi5fC9fsT6l7IkPBg4mJsOilEJvbPTzR+alooxmbocgxjs45nILhZrajDrC/qXXrNbOsgCji48At77tfaUDbB4tiQfT7TyADv4/+mkgz3+yAY6NgPnBFhNbWGo7DIAgeUxSEs+lIvikeHDG04opMMRb+76H/erxzlkEMYx59FMDVYF7ALXAs3idPK8oHGsN4rkCnidsGEEEMlRXie8Imf38eAKYQ7KBVjUP4boPoB6KzfzADaTHoM8eYJsQlXxtffdky6nD6hcfmGG/HySNkL/6X3Nl2Fx8RPu5J1BwpeO0xmyzVWF/gVRyyW2JOcI5pGu7TclCjkSHgWfdWrCwao2UGxwDCXgSzkTk9E6UdG+iLmtWEkpSKRf33FNOD5vrccTwFBI9Oaa5AGuJnLUnVjsKz9OW02bXIRMweazwvoCiS9xEp36s=
  on:
    tags: true
    python: 3.6
